### ISSUE TITLE
Design configuration format

### ISSUE THREAD

**Issue by prasadtalasila** [INTO-CPS-Association/simulation-bridge#3]
The configuration schema of the simulation bridge needs to be defined. The current schema is

```yml
mqtt:
  broker: "test.mosquitto.org"
  port: 1883
simulations:
  matlab:
    input_topic: "sim/matlab/input"
    output_topic: "sim/matlab/output"
  analogic:
    input_topic: "sim/analogic/input"
    output_topic: "sim/analogic/output"
  python:
    input_topic: "sim/python/input"
    output_topic: "sim/python/output"
timeout: 10
```

**Comment by marcomelloni** [comment]
```yaml
# Unique identifier for this simulation bridge instance
simulation_bridge:
  bridge_id: simulation_bridge # ID used to identify this instance of the sim-bridge

# RabbitMQ protocol adapter configuration
rabbitmq:
  host: localhost # RabbitMQ broker hostname or IP address
  port: 5672 # Port for non-TLS AMQP connections (default: 5672)
  vhost: / # Virtual host used in RabbitMQ
  username: guest # Username for RabbitMQ authentication
  password: guest # Password for RabbitMQ authentication
  tls: false # Whether to use TLS (amqps) or not

  infrastructure:
    exchanges:
      - name: ex.input.bridge # Exchange for receiving input messages from external systems
        type: topic # Exchange type (topic allows pattern-based routing)
        durable: true # Exchange survives broker restarts
        auto_delete: false # Exchange won't be deleted when no longer used
        internal: false # Exchange is available to external producers

      - name: ex.bridge.output # Exchange for sending output messages to external systems
        type: topic
        durable: true
        auto_delete: false
        internal: false

      - name: ex.sim.result # Exchange for simulation result messages
        type: topic
        durable: true
        auto_delete: false
        internal: false

      - name: ex.bridge.result # Exchange for bridge-processed results
        type: topic
        durable: true
        auto_delete: false
        internal: false

    queues:
      - name: Q.bridge.input # Queue for receiving messages intended for the bridge
        durable: true # Queue survives broker restarts
        exclusive: false # Queue is not exclusive to one connection
        auto_delete: false # Queue will not be deleted automatically

      - name: Q.bridge.result # Queue for receiving simulation results
        durable: true
        exclusive: false
        auto_delete: false

    bindings:
      - queue: Q.bridge.input # Bind the input queue...
        exchange: ex.input.bridge # ...to this exchange...
        routing_key: "#" # ...with wildcard routing (all messages)

      - queue: Q.bridge.result # Bind the result queue...
        exchange: ex.sim.result # ...to receive all simulation result messages
        routing_key: "#" # ...with wildcard routing

# MQTT protocol adapter configuration
mqtt:
  host: localhost # MQTT broker hostname or IP
  port: 1883 # Port for MQTT (1883 for non-TLS, 8883 for TLS)
  keepalive: 60 # Keep-alive interval in seconds for MQTT client
  input_topic: bridge/input # Topic to subscribe to for receiving messages
  output_topic: bridge/output # Topic to publish processed messages to
  qos: 0 # Quality of Service level (0 = at most once)
  username: guest # Username for MQTT authentication
  password: guest # Password for MQTT authentication
  tls: false # Whether to use secure MQTT (mqtts) or not

# REST protocol adapter configuration
rest:
  host: 0.0.0.0 # REST API binds to all network interfaces
  port: 5000 # Port for RESTful HTTP server
  endpoint: /message # Endpoint path for sending messages to the bridge
  debug: false # Disable Flask debug mode (set to true for development)
  certfile: certs/cert.pem # Path to the TLS certificate file for HTTPS
  keyfile: certs/key.pem # Path to the private key file for HTTPS
  jwt: # JWT configuration for secure token-based authentication
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_VALUE" # Secret key for signing JWT tokens
    algorithm: HS256 # Algorithm used for signing JWT tokens
    max_token_age_seconds: 3600 # Maximum age of JWT tokens in seconds (1 hour)

# Logging configuration
logging:
  level: INFO # Logging level (e.g., DEBUG, INFO, WARNING, ERROR)
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s" # Format of log messages
  file: logs/sim_bridge.log # Path to the log output file

# Performance monitoring configuration
performance:
  enabled: false # Enable/disable performance monitoring
  file: performance_log/performance_metrics.csv # File where performance logs will be stored
```
